require('dotenv').config();
const mongoose = require('mongoose');
const Country = require('./models/country')

const countries = [
    {countryCode: "AF",continent: "Asia"},
    {countryCode: "AX",continent: "Europe"},
    {countryCode: "AL",continent: "Europe"},
    {countryCode: "DZ",continent: "Africa"},
    {countryCode: "AS",continent: "Oceania"},
    {countryCode: "AD",continent: "Europe"},
    {countryCode: "AO",continent: "Africa"},
    {countryCode: "AI",continent: "North America"},
    {countryCode: "AQ",continent: "Antarctica"},
    {countryCode: "AG",continent: "North America"},
    {countryCode: "AR",continent: "South America"},
    {countryCode: "AM",continent: "Asia"},
    {countryCode: "AW",continent: "North America"},
    {countryCode: "AU",continent: "Oceania"},
    {countryCode: "AT",continent: "Europe"},
    {countryCode: "AZ",continent: "Asia"},
    {countryCode: "BS",continent: "North America"},
    {countryCode: "BH",continent: "Asia"},
    {countryCode: "BD",continent: "Asia"},
    {countryCode: "BB",continent: "North America"},
    {countryCode: "BY",continent: "Europe"},
    {countryCode: "BE",continent: "Europe"},
    {countryCode: "BZ",continent: "North America"},
    {countryCode: "BJ",continent: "Africa"},
    {countryCode: "BM",continent: "North America"},
    {countryCode: "BT",continent: "Asia"},
    {countryCode: "BO",continent: "South America"},
    {countryCode: "BQ",continent: "North America"},
    {countryCode: "BA",continent: "Europe"},
    {countryCode: "BW",continent: "Africa"},
    {countryCode: "BV",continent: "Antarctica"},
    {countryCode: "BR",continent: "South America"},
    {countryCode: "IO",continent: "Asia"},
    {countryCode: "BN",continent: "Asia"},
    {countryCode: "BG",continent: "Europe"},
    {countryCode: "BF",continent: "Africa"},
    {countryCode: "BI",continent: "Africa"},
    {countryCode: "KH",continent: "Asia"},
    {countryCode: "CM",continent: "Africa"},
    {countryCode: "CA",continent: "North America"},
    {countryCode: "CV",continent: "Africa"},
    {countryCode: "KY",continent: "North America"},
    {countryCode: "CF",continent: "Africa"},
    {countryCode: "TD",continent: "Africa"},
    {countryCode: "CL",continent: "South America"},
    {countryCode: "CN",continent: "Asia"},
    {countryCode: "CX",continent: "Asia"},
    {countryCode: "CC",continent: "Asia"},
    {countryCode: "CO",continent: "South America"},
    {countryCode: "KM",continent: "Africa"},
    {countryCode: "CG",continent: "Africa"},
    {countryCode: "CD",continent: "Africa"},
    {countryCode: "CK",continent: "Oceania"},
    {countryCode: "CR",continent: "North America"},
    {countryCode: "CI",continent: "Africa"},
    {countryCode: "HR",continent: "Europe"},
    {countryCode: "CU",continent: "North America"},
    {countryCode: "CW",continent: "North America"},
    {countryCode: "CY",continent: "Asia"},
    {countryCode: "CZ",continent: "Europe"},
    {countryCode: "DK",continent: "Europe"},
    {countryCode: "DJ",continent: "Africa"},
    {countryCode: "DM",continent: "North America"},
    {countryCode: "DO",continent: "North America"},
    {countryCode: "EC",continent: "South America"},
    {countryCode: "EG",continent: "Africa"},
    {countryCode: "SV",continent: "North America"},
    {countryCode: "GQ",continent: "Africa"},
    {countryCode: "ER",continent: "Africa"},
    {countryCode: "EE",continent: "Europe"},
    {countryCode: "ET",continent: "Africa"},
    {countryCode: "FK",continent: "South America"},
    {countryCode: "FO",continent: "Europe"},
    {countryCode: "FJ",continent: "Oceania"},
    {countryCode: "FI",continent: "Europe"},
    {countryCode: "FR",continent: "Europe"},
    {countryCode: "GF",continent: "South America"},
    {countryCode: "PF",continent: "Oceania"},
    {countryCode: "TF",continent: "Antarctica"},
    {countryCode: "GA",continent: "Africa"},
    {countryCode: "GM",continent: "Africa"},
    {countryCode: "GE",continent: "Asia"},
    {countryCode: "DE",continent: "Europe"},
    {countryCode: "GH",continent: "Africa"},
    {countryCode: "GI",continent: "Europe"},
    {countryCode: "GR",continent: "Europe"},
    {countryCode: "GL",continent: "North America"},
    {countryCode: "GD",continent: "North America"},
    {countryCode: "GP",continent: "North America"},
    {countryCode: "GU",continent: "Oceania"},
    {countryCode: "GT",continent: "North America"},
    {countryCode: "GG",continent: "Europe"},
    {countryCode: "GN",continent: "Africa"},
    {countryCode: "GW",continent: "Africa"},
    {countryCode: "GY",continent: "South America"},
    {countryCode: "HT",continent: "North America"},
    {countryCode: "HM",continent: "Antarctica"},
    {countryCode: "VA",continent: "Europe"},
    {countryCode: "HN",continent: "North America"},
    {countryCode: "HK",continent: "Asia"},
    {countryCode: "HU",continent: "Europe"},
    {countryCode: "IS",continent: "Europe"},
    {countryCode: "IN",continent: "Asia"},
    {countryCode: "ID",continent: "Asia"},
    {countryCode: "IR",continent: "Asia"},
    {countryCode: "IQ",continent: "Asia"},
    {countryCode: "IE",continent: "Europe"},
    {countryCode: "IM",continent: "Europe"},
    {countryCode: "IL",continent: "Asia"},
    {countryCode: "IT",continent: "Europe"},
    {countryCode: "JM",continent: "North America"},
    {countryCode: "JP",continent: "Asia"},
    {countryCode: "JE",continent: "Europe"},
    {countryCode: "JO",continent: "Asia"},
    {countryCode: "KZ",continent: "Asia"},
    {countryCode: "KE",continent: "Africa"},
    {countryCode: "KI",continent: "Oceania"},
    {countryCode: "KP",continent: "Asia"},
    {countryCode: "KR",continent: "Asia"},
    {countryCode: "XK",continent: "Europe"},
    {countryCode: "KW",continent: "Asia"},
    {countryCode: "KG",continent: "Asia"},
    {countryCode: "LA",continent: "Asia"},
    {countryCode: "LV",continent: "Europe"},
    {countryCode: "LB",continent: "Asia"},
    {countryCode: "LS",continent: "Africa"},
    {countryCode: "LR",continent: "Africa"},
    {countryCode: "LY",continent: "Africa"},
    {countryCode: "LI",continent: "Europe"},
    {countryCode: "LT",continent: "Europe"},
    {countryCode: "LU",continent: "Europe"},
    {countryCode: "MO",continent: "Asia"},
    {countryCode: "MK",continent: "Europe"},
    {countryCode: "MG",continent: "Africa"},
    {countryCode: "MW",continent: "Africa"},
    {countryCode: "MY",continent: "Asia"},
    {countryCode: "MV",continent: "Asia"},
    {countryCode: "ML",continent: "Africa"},
    {countryCode: "MT",continent: "Europe"},
    {countryCode: "MH",continent: "Oceania"},
    {countryCode: "MQ",continent: "North America"},
    {countryCode: "MR",continent: "Africa"},
    {countryCode: "MU",continent: "Africa"},
    {countryCode: "YT",continent: "Africa"},
    {countryCode: "MX",continent: "North America"},
    {countryCode: "FM",continent: "Oceania"},
    {countryCode: "MD",continent: "Europe"},
    {countryCode: "MC",continent: "Europe"},
    {countryCode: "MN",continent: "Asia"},
    {countryCode: "ME",continent: "Europe"},
    {countryCode: "MS",continent: "North America"},
    {countryCode: "MA",continent: "Africa"},
    {countryCode: "MZ",continent: "Africa"},
    {countryCode: "MM",continent: "Asia"},
    {countryCode: "NA",continent: "Africa"},
    {countryCode: "NR",continent: "Oceania"},
    {countryCode: "NP",continent: "Asia"},
    {countryCode: "NL",continent: "Europe"},
    {countryCode: "AN",continent: "North America"},
    {countryCode: "NC",continent: "Oceania"},
    {countryCode: "NZ",continent: "Oceania"},
    {countryCode: "NI",continent: "North America"},
    {countryCode: "NE",continent: "Africa"},
    {countryCode: "NG",continent: "Africa"},
    {countryCode: "NU",continent: "Oceania"},
    {countryCode: "NF",continent: "Oceania"},
    {countryCode: "MP",continent: "Oceania"},
    {countryCode: "NO",continent: "Europe"},
    {countryCode: "OM",continent: "Asia"},
    {countryCode: "PK",continent: "Asia"},
    {countryCode: "PW",continent: "Oceania"},
    {countryCode: "PS",continent: "Asia"},
    {countryCode: "PA",continent: "North America"},
    {countryCode: "PG",continent: "Oceania"},
    {countryCode: "PY",continent: "South America"},
    {countryCode: "PE",continent: "South America"},
    {countryCode: "PH",continent: "Asia"},
    {countryCode: "PN",continent: "Oceania"},
    {countryCode: "PL",continent: "Europe"},
    {countryCode: "PT",continent: "Europe"},
    {countryCode: "PR",continent: "North America"},
    {countryCode: "QA",continent: "Asia"},
    {countryCode: "RE",continent: "Africa"},
    {countryCode: "RO",continent: "Europe"},
    {countryCode: "RU",continent: "Asia"},
    {countryCode: "RW",continent: "Africa"},
    {countryCode: "BL",continent: "North America"},
    {countryCode: "SH",continent: "Africa"},
    {countryCode: "KN",continent: "North America"},
    {countryCode: "LC",continent: "North America"},
    {countryCode: "MF",continent: "North America"},
    {countryCode: "PM",continent: "North America"},
    {countryCode: "VC",continent: "North America"},
    {countryCode: "WS",continent: "Oceania"},
    {countryCode: "SM",continent: "Europe"},
    {countryCode: "ST",continent: "Africa"},
    {countryCode: "SA",continent: "Asia"},
    {countryCode: "SN",continent: "Africa"},
    {countryCode: "RS",continent: "Europe"},
    {countryCode: "CS",continent: "Europe"},
    {countryCode: "SC",continent: "Africa"},
    {countryCode: "SL",continent: "Africa"},
    {countryCode: "SG",continent: "Asia"},
    {countryCode: "SX",continent: "North America"},
    {countryCode: "SK",continent: "Europe"},
    {countryCode: "SI",continent: "Europe"},
    {countryCode: "SB",continent: "Oceania"},
    {countryCode: "SO",continent: "Africa"},
    {countryCode: "ZA",continent: "Africa"},
    {countryCode: "GS",continent: "Antarctica"},
    {countryCode: "SS",continent: "Africa"},
    {countryCode: "ES",continent: "Europe"},
    {countryCode: "LK",continent: "Asia"},
    {countryCode: "SD",continent: "Africa"},
    {countryCode: "SR",continent: "South America"},
    {countryCode: "SJ",continent: "Europe"},
    {countryCode: "SZ",continent: "Africa"},
    {countryCode: "SE",continent: "Europe"},
    {countryCode: "CH",continent: "Europe"},
    {countryCode: "SY",continent: "Asia"},
    {countryCode: "TW",continent: "Asia"},
    {countryCode: "TJ",continent: "Asia"},
    {countryCode: "TZ",continent: "Africa"},
    {countryCode: "TH",continent: "Asia"},
    {countryCode: "TL",continent: "Asia"},
    {countryCode: "TG",continent: "Africa"},
    {countryCode: "TK",continent: "Oceania"},
    {countryCode: "TO",continent: "Oceania"},
    {countryCode: "TT",continent: "North America"},
    {countryCode: "TN",continent: "Africa"},
    {countryCode: "TR",continent: "Asia"},
    {countryCode: "TM",continent: "Asia"},
    {countryCode: "TC",continent: "North America"},
    {countryCode: "TV",continent: "Oceania"},
    {countryCode: "UG",continent: "Africa"},
    {countryCode: "UA",continent: "Europe"},
    {countryCode: "AE",continent: "Asia"},
    {countryCode: "GB",continent: "Europe"},
    {countryCode: "US",continent: "North America"},
    {countryCode: "UM",continent: "North America"},
    {countryCode: "UY",continent: "South America"},
    {countryCode: "UZ",continent: "Asia"},
    {countryCode: "VU",continent: "Oceania"},
    {countryCode: "VE",continent: "South America"},
    {countryCode: "VN",continent: "Asia"},
    {countryCode: "VG",continent: "North America"},
    {countryCode: "VI",continent: "North America"},
    {countryCode: "WF",continent: "Oceania"},
    {countryCode: "EH",continent: "Africa"},
    {countryCode: "YE",continent: "Asia"},
    {countryCode: "ZM",continent: "Africa"},
    {countryCode: "ZW",continent: "Africa"}
];

async function seed() {
    mongoose.connect(process.env.MONGODB_URI)

    const countriesinDb = await Country.find()

    countries.forEach(country => {
        countriesinDb.forEach(async (countryinDb) => {
            if (country.countryCode === countryinDb.countryCode) {
                countryinDb.continent = country.continent
                await countryinDb.save()
            }
        })
    })

}

seed()